# Generated by Django 4.1.6 on 2023-02-03 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('area',),
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('solicitante',),
            },
        ),
        migrations.CreateModel(
            name='Romaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(verbose_name='Data de Entrada')),
                ('nf', models.CharField(blank=True, max_length=15, null=True, verbose_name='NF')),
                ('romaneio', models.CharField(max_length=15, unique=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='documento referência')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.area')),
                ('funcionario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.solicitante')),
            ],
            options={
                'ordering': ('romaneio',),
            },
        ),
    ]
