# Generated by Django 4.1.6 on 2023-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0002_alter_romaneio_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romaneio',
            name='obs',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Obs'),
        ),
    ]
