# Generated by Django 4.1.6 on 2023-02-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0003_alter_romaneio_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romaneio',
            name='entrada',
            field=models.DateField(verbose_name='Data de Entrada'),
        ),
    ]
