# Generated by Django 4.1.6 on 2023-02-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('romaneio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TintaAcabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinta_acabamento', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('tinta_acabamento',),
            },
        ),
        migrations.CreateModel(
            name='TintaFundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinta_fundo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('tinta_fundo',),
            },
        ),
        migrations.CreateModel(
            name='TintaIntermediaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinta_intermediaria', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('tinta_intermediaria',),
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamento', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('tratamento',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('cor', models.CharField(blank=True, max_length=15, null=True)),
                ('material', models.CharField(choices=[], max_length=15)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
                ('polegada', models.CharField(max_length=4, verbose_name='polegas separadas por ","')),
                ('m_quantidade', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Metro ou Quantidade')),
                ('m2', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Metro ou Quantidade')),
                ('jato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.tratamento')),
                ('n_romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.romaneio')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.tintaacabamento')),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.tintafundo')),
                ('ti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.tintaintermediaria')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
