# Generated by Django 4.1.6 on 2023-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(choices=[('perfil_I', ''), ('perfil_H', ''), ('perfil_U', ''), ('perfil_L', ''), ('barra_chata', ''), ('tubulacao', ''), ('acess_T', ''), ('acess_FLG', ''), ('acess_RED', ''), ('acess_CV90', ''), ('acess_CV45', ''), ('acess_VV', ''), ('acess_VVC', ''), ('acess_CAP', '')], max_length=15),
        ),
    ]
