# Generated by Django 4.1.6 on 2023-02-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_material_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='jato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.tratamento'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.tintaacabamento'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.tintafundo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.tintaintermediaria'),
        ),
    ]
