# Generated by Django 4.1.6 on 2023-02-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_jato_alter_material_ta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(choices=[('perfil_I', 'perfil_I'), ('perfil_H', 'perfil_H'), ('perfil_U', 'perfil_U'), ('perfil_L', 'perfil_L'), ('barra_chata', 'barra_chata'), ('tubulacao', 'tubulacao'), ('acess_T', 'acess_T'), ('acess_FLG', 'acess_FLG'), ('acess_RED', 'acess_RED'), ('acess_CV90', 'acess_CV90'), ('acess_CV45', 'acess_CV45'), ('acess_VV', 'acess_VV'), ('acess_VVC', 'acess_VVC'), ('acess_CAP', 'acess_CAP')], max_length=15),
        ),
    ]
