# Generated by Django 4.1.6 on 2023-02-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0002_alter_romaneio_funcionario'),
        ('material', '0004_alter_material_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='m2',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='M²'),
        ),
        migrations.AlterField(
            model_name='material',
            name='m_quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M/QTD'),
        ),
        migrations.AlterField(
            model_name='material',
            name='n_romaneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='romaneios', to='romaneio.romaneio'),
        ),
        migrations.AlterField(
            model_name='material',
            name='polegada',
            field=models.CharField(max_length=4, verbose_name='Pol'),
        ),
    ]
