# Generated by Django 4.1.6 on 2023-02-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_alter_material_m2_alter_material_m_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
