# Generated by Django 4.1.6 on 2023-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_material_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição'),
        ),
    ]
