# Generated by Django 4.1.6 on 2023-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_alter_material_m2_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='equipamento',
            field=models.CharField(choices=[('carretel', 'carretel'), ('boleado', 'boleado'), ('cone', 'cone'), ('janela', 'janela'), ('cubo', 'cubo')], max_length=30),
        ),
    ]
