# Generated by Django 4.1.6 on 2023-02-13 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_equipamento_concluido_alter_equipamento_equipamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='equipamento',
            field=models.CharField(choices=[('cone', 'cone'), ('boleado', 'boleado'), ('janela', 'janela'), ('cubo', 'cubo'), ('carretel', 'carretel')], max_length=30),
        ),
    ]
