# Generated by Django 4.1.6 on 2023-02-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_alter_equipamento_options_equipamento_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='jato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.tratamento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.tintaacabamento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.tintafundo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.tintaintermediaria'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='equipamento',
            field=models.CharField(choices=[('cubo', 'cubo'), ('cone', 'cone'), ('janela', 'janela'), ('boleado', 'boleado'), ('carretel', 'carretel')], max_length=30),
        ),
    ]
