# Generated by Django 4.1.6 on 2023-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_material_altura_material_comprimento_material_lados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='equipamento',
            field=models.CharField(choices=[('boleado', 'boleado'), ('janela', 'janela'), ('cubo', 'cubo'), ('cone', 'cone'), ('carretel', 'carretel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='lados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='lados/QTD'),
        ),
        migrations.AlterField(
            model_name='material',
            name='m2',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='M²'),
        ),
        migrations.AlterField(
            model_name='material',
            name='m_quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='M/QTD'),
        ),
        migrations.AlterField(
            model_name='material',
            name='polegada',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Pol'),
        ),
    ]
