# Generated by Django 4.1.6 on 2023-02-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_alter_equipamento_equipamento_alter_material_lados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='comprimento/lados'),
        ),
        migrations.AlterField(
            model_name='material',
            name='lados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='QTD'),
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
