# Generated by Django 4.1.7 on 2023-03-25 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('romaneio', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMF',
            fields=[
                ('bmf', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('data_periodo', models.DateField(verbose_name='Período')),
                ('rev', models.IntegerField(blank=True, null=True, verbose_name='Espessura seca')),
                ('auth_serv', models.CharField(max_length=80, verbose_name='AS')),
                ('escopo', models.CharField(max_length=80, verbose_name='Escopo do serviço')),
                ('local', models.CharField(max_length=80, verbose_name='Local do serviço')),
                ('id_serv', models.CharField(max_length=80, verbose_name='ID serviço')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo')),
                ('valor', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Valor')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('contrato',),
            },
        ),
        migrations.CreateModel(
            name='DMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ref', models.CharField(max_length=10, unique=True)),
                ('disciplina', models.CharField(choices=[('Andaime', 'Andaime'), ('Pintura', 'Pintura'), ('Isolamento', 'Isolamento')], max_length=20)),
                ('descricao', models.CharField(max_length=80)),
                ('und', models.CharField(choices=[('m', 'm'), ('m2', 'm2'), ('m3', 'm3'), ('und', 'und')], max_length=3)),
                ('preco_item', models.DecimalField(decimal_places=3, max_digits=11, verbose_name='Preço')),
                ('qtd', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Quantidade')),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Total')),
                ('bmf', models.ManyToManyField(to='financeiro.bmf')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contrato')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='bmf',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contrato'),
        ),
        migrations.AddField(
            model_name='bmf',
            name='dms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dms', to='financeiro.dms'),
        ),
        migrations.AddField(
            model_name='bmf',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bmf',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.solicitante'),
        ),
        migrations.AddField(
            model_name='bmf',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.area'),
        ),
    ]
