# Generated by Django 4.1.7 on 2023-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_itembm_bmf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembm',
            name='bmf',
        ),
        migrations.AddField(
            model_name='bmf',
            name='item_bm',
            field=models.ManyToManyField(blank=True, null=True, to='financeiro.itembm'),
        ),
        migrations.AlterField(
            model_name='bmf',
            name='rev',
            field=models.IntegerField(blank=True, null=True, verbose_name='Revisão'),
        ),
    ]
