# Generated by Django 4.1.7 on 2023-03-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_bmf_item_bm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembm',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='itembm',
            name='total',
        ),
    ]
