# Generated by Django 4.1.7 on 2023-03-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_remove_itembm_qtd_remove_itembm_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='QtdBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='qtd')),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='total')),
                ('bmf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.bmf')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.itembm')),
            ],
        ),
    ]
