# Generated by Django 4.1.7 on 2023-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_qtdbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtdbm',
            name='qtd',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=11, verbose_name='qtd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qtdbm',
            name='total',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=11, verbose_name='total'),
            preserve_default=False,
        ),
    ]
