# Generated by Django 4.1.7 on 2023-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_aprovador_frs_dms_data_aprov_dms_dms_n_dms_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bms',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='dms',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='frs',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='bms',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='dms',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='frs',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='frs',
            name='data_emissão',
            field=models.DateField(blank=True, null=True, verbose_name='Emissão nota'),
        ),
    ]
