# Generated by Django 4.1.7 on 2023-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_alter_bms_options_alter_dms_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembm',
            name='disciplina',
            field=models.CharField(choices=[('ANDAIME', 'ANDAIME'), ('PINTURA', 'PINTURA'), ('ISOLAMENTO', 'ISOLAMENTO'), ('GERAL', 'GERAL'), ('ALTA DENSIDADE', 'ALTA DENSIDADE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itembm',
            name='und',
            field=models.CharField(choices=[('M', 'M'), ('M2', 'M2'), ('M3', 'M3'), ('UN', 'UN'), ('VAL', 'VAL'), ('H', 'H')], max_length=3),
        ),
    ]
