# Generated by Django 4.1.7 on 2023-03-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_alter_itembm_disciplina_alter_itembm_und'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmf',
            name='escopo',
            field=models.CharField(max_length=120, verbose_name='Escopo do serviço'),
        ),
    ]
