# Generated by Django 4.1.7 on 2023-04-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_alter_bmf_escopo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmf',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='bmfs/', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='bmf',
            name='follow_up',
            field=models.TextField(blank=True, null=True, verbose_name='Obs/followup'),
        ),
        migrations.AddField(
            model_name='bms',
            name='follow_up',
            field=models.TextField(blank=True, null=True, verbose_name='Obs/followup'),
        ),
        migrations.AddField(
            model_name='dms',
            name='follow_up',
            field=models.TextField(blank=True, null=True, verbose_name='Obs/followup'),
        ),
        migrations.AddField(
            model_name='frs',
            name='follow_up',
            field=models.TextField(blank=True, null=True, verbose_name='Obs/followup'),
        ),
    ]
