# Generated by Django 4.1.7 on 2023-02-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioinspecao',
            name='corrosividade',
            field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6')], max_length=15),
        ),
        migrations.AlterField(
            model_name='relatorioinspecao',
            name='rugosidade',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rugosidade'),
        ),
    ]
