# Generated by Django 4.1.7 on 2023-02-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_alter_relatorioinspecao_corrosividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioinspecao',
            name='tratamento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tratamento'),
        ),
    ]
