# Generated by Django 4.2.3 on 2023-11-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('romaneio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprovador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovador', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='AS',
            fields=[
                ('a_s', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('data_periodo', models.DateField(verbose_name='Período')),
                ('escopo', models.CharField(max_length=120, verbose_name='Escopo do serviço')),
                ('local', models.CharField(max_length=80, verbose_name='Local do serviço')),
                ('valor', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Valor')),
                ('doc', models.FileField(blank=True, null=True, upload_to='as/', verbose_name='documento')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BoletimMedicao',
            fields=[
                ('bm_n', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('d_numero', models.CharField(max_length=40, verbose_name='Dms')),
                ('status', models.CharField(choices=[('APROVADO', 'APROVADO'), ('AGUARDANDO OM', 'AGUARDANDO OM'), ('EM LANÇAMENTO', 'EM LANÇAMENTO'), ('NÃO APROVADO', 'NÃO APROVADO'), ('REPROVADO', 'REPROVADO')], max_length=20)),
                ('data_aprov', models.DateField(blank=True, null=True, verbose_name='Aprovação')),
                ('valor', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Valor')),
                ('follow_up', models.TextField(blank=True, null=True, verbose_name='Obs/followup')),
                ('rev', models.IntegerField(default=0, verbose_name='Revisão')),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.aprovador')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('contrato',),
            },
        ),
        migrations.CreateModel(
            name='FRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('frs_n', models.CharField(max_length=20, unique=True)),
                ('status_frs', models.CharField(choices=[('AGUARDANDO', 'AGUARDANDO'), ('GERADA', 'GERADA'), ('OM EXCEDIDADE', 'OM EXCEDIDADE')], max_length=20)),
                ('data_aprov', models.DateField(blank=True, null=True, verbose_name='Aprovação')),
                ('nf', models.CharField(max_length=30, unique=True)),
                ('data_emissão', models.DateField(blank=True, null=True, verbose_name='Emissão nota')),
                ('status_nf', models.CharField(choices=[('AGUARDANDO', 'AGUARDANDO'), ('GERADA', 'GERADA'), ('OM EXCEDIDADE', 'OM EXCEDIDADE')], max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Valor')),
                ('follow_up', models.TextField(blank=True, null=True, verbose_name='Obs/followup')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ItemBm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ref', models.CharField(max_length=10, unique=True)),
                ('disciplina', models.CharField(choices=[('ANDAIME', 'ANDAIME'), ('PINTURA', 'PINTURA'), ('ISOLAMENTO', 'ISOLAMENTO'), ('GERAL', 'GERAL')], max_length=20)),
                ('descricao', models.CharField(max_length=80)),
                ('und', models.CharField(choices=[('M', 'M'), ('M2', 'M2'), ('M3', 'M3'), ('UN', 'UN'), ('VAL', 'VAL'), ('H', 'H')], max_length=3)),
                ('preco_item', models.DecimalField(decimal_places=3, max_digits=11, verbose_name='Preço')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.contrato')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='RDO',
            fields=[
                ('rdo', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('data_periodo', models.DateField(verbose_name='Período')),
                ('disciplina', models.CharField(choices=[('ANDAIME', 'ANDAIME'), ('PINTURA', 'PINTURA'), ('ISOLAMENTO', 'ISOLAMENTO'), ('GERAL', 'GERAL')], max_length=20)),
                ('auth_serv', models.CharField(blank=True, max_length=80, null=True, verbose_name='AS')),
                ('escopo', models.CharField(max_length=120, verbose_name='Escopo do serviço')),
                ('local', models.CharField(max_length=80, verbose_name='Local do serviço')),
                ('tipo', models.CharField(choices=[('PARADA', 'PARADA'), ('PACOTE', 'PACOTE'), ('ROTINA', 'ROTINA'), ('PROJETO', 'PROJETO')], max_length=20, verbose_name='Tipo Serviço')),
                ('clima', models.CharField(choices=[('BOM', 'BOM'), ('NUBLADO', 'NUBLADO'), ('CHUVOSO', 'CHUVOSO')], max_length=20, verbose_name='Clima')),
                ('valor', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Valor')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('termino', models.DateTimeField(verbose_name='Fim')),
                ('doc', models.FileField(blank=True, null=True, upload_to='bmfs/', verbose_name='documento')),
                ('slug', models.SlugField(default='')),
                ('bm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms', to='rdo.boletimmedicao')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.contrato')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_bm', models.ManyToManyField(blank=True, to='rdo.itembm')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.solicitante')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.area')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='QtdBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efetivo', models.IntegerField(verbose_name='Efetivo')),
                ('qtd', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='qtd')),
                ('total', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='total')),
                ('bmf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.rdo')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.itembm')),
            ],
        ),
        migrations.CreateModel(
            name='QtdAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='qtd')),
                ('total', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='total')),
                ('a_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.as')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.itembm')),
            ],
        ),
        migrations.AddField(
            model_name='boletimmedicao',
            name='frs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frs', to='rdo.frs'),
        ),
        migrations.AddField(
            model_name='as',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.contrato'),
        ),
        migrations.AddField(
            model_name='as',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='as',
            name='item_bm',
            field=models.ManyToManyField(blank=True, to='rdo.itembm'),
        ),
        migrations.AddField(
            model_name='as',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.solicitante'),
        ),
        migrations.AddField(
            model_name='as',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneio.area'),
        ),
        migrations.AddField(
            model_name='aprovador',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdo.contrato'),
        ),
    ]
